### ISSUE TITLE
TUB to deploy Keycloak to enable UC to start defining users and roles and integrate with the apps

### ISSUE THREAD

**Issue by AitorF** [DITAS-Project/TUBPM#7]
_(I open it here as I haven't found a more convinient place - feel free to tell to move it)_

We are ready to integrate our applications with Keycloak as soon as we have a Keycloak service running.

**Comment by tawalaya** [comment]
Hi @AitorF we are still working on the keycloak setup and it will be at least tow weeks before we have anything. If you want to start integrating locally you can use the https://cloud.docker.com/u/ditas/repository/docker/ditas/keycloak image it exposes a normal keycloak installation. 

to optain a token you can call url:8080/auth/realms/vdc_access/protocol/openid-connect/token this url. you need to **POST** to it with url-encoded body `username:test password:test grant_type:password`
this will give you a token.
